// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/IMMessage.proto

package com.linseven.protobuf;

public final class IMMessageOuterClass {
  private IMMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IMMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.linseven.protobuf.IMMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sourceUserId = 1;</code>
     * @return The sourceUserId.
     */
    int getSourceUserId();

    /**
     * <code>int32 destUserId = 2;</code>
     * @return The destUserId.
     */
    int getDestUserId();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>int32 groupId = 5;</code>
     * @return The groupId.
     */
    int getGroupId();

    /**
     * <code>int64 sendTime = 6;</code>
     * @return The sendTime.
     */
    long getSendTime();
  }
  /**
   * Protobuf type {@code com.linseven.protobuf.IMMessage}
   */
  public static final class IMMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.linseven.protobuf.IMMessage)
      IMMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IMMessage.newBuilder() to construct.
    private IMMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IMMessage() {
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new IMMessage();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.linseven.protobuf.IMMessageOuterClass.internal_static_com_linseven_protobuf_IMMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.linseven.protobuf.IMMessageOuterClass.internal_static_com_linseven_protobuf_IMMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.linseven.protobuf.IMMessageOuterClass.IMMessage.class, com.linseven.protobuf.IMMessageOuterClass.IMMessage.Builder.class);
    }

    public static final int SOURCEUSERID_FIELD_NUMBER = 1;
    private int sourceUserId_ = 0;
    /**
     * <code>int32 sourceUserId = 1;</code>
     * @return The sourceUserId.
     */
    @java.lang.Override
    public int getSourceUserId() {
      return sourceUserId_;
    }

    public static final int DESTUSERID_FIELD_NUMBER = 2;
    private int destUserId_ = 0;
    /**
     * <code>int32 destUserId = 2;</code>
     * @return The destUserId.
     */
    @java.lang.Override
    public int getDestUserId() {
      return destUserId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    @java.lang.Override
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_ = 0;
    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int GROUPID_FIELD_NUMBER = 5;
    private int groupId_ = 0;
    /**
     * <code>int32 groupId = 5;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public int getGroupId() {
      return groupId_;
    }

    public static final int SENDTIME_FIELD_NUMBER = 6;
    private long sendTime_ = 0L;
    /**
     * <code>int64 sendTime = 6;</code>
     * @return The sendTime.
     */
    @java.lang.Override
    public long getSendTime() {
      return sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sourceUserId_ != 0) {
        output.writeInt32(1, sourceUserId_);
      }
      if (destUserId_ != 0) {
        output.writeInt32(2, destUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      if (groupId_ != 0) {
        output.writeInt32(5, groupId_);
      }
      if (sendTime_ != 0L) {
        output.writeInt64(6, sendTime_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sourceUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sourceUserId_);
      }
      if (destUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, destUserId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(content_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (groupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, groupId_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sendTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.linseven.protobuf.IMMessageOuterClass.IMMessage)) {
        return super.equals(obj);
      }
      com.linseven.protobuf.IMMessageOuterClass.IMMessage other = (com.linseven.protobuf.IMMessageOuterClass.IMMessage) obj;

      if (getSourceUserId()
          != other.getSourceUserId()) return false;
      if (getDestUserId()
          != other.getDestUserId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getType()
          != other.getType()) return false;
      if (getGroupId()
          != other.getGroupId()) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOURCEUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getSourceUserId();
      hash = (37 * hash) + DESTUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getDestUserId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.linseven.protobuf.IMMessageOuterClass.IMMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.linseven.protobuf.IMMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.linseven.protobuf.IMMessage)
        com.linseven.protobuf.IMMessageOuterClass.IMMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.linseven.protobuf.IMMessageOuterClass.internal_static_com_linseven_protobuf_IMMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.linseven.protobuf.IMMessageOuterClass.internal_static_com_linseven_protobuf_IMMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.linseven.protobuf.IMMessageOuterClass.IMMessage.class, com.linseven.protobuf.IMMessageOuterClass.IMMessage.Builder.class);
      }

      // Construct using com.linseven.protobuf.IMMessageOuterClass.IMMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sourceUserId_ = 0;
        destUserId_ = 0;
        content_ = "";
        type_ = 0;
        groupId_ = 0;
        sendTime_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.linseven.protobuf.IMMessageOuterClass.internal_static_com_linseven_protobuf_IMMessage_descriptor;
      }

      @java.lang.Override
      public com.linseven.protobuf.IMMessageOuterClass.IMMessage getDefaultInstanceForType() {
        return com.linseven.protobuf.IMMessageOuterClass.IMMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.linseven.protobuf.IMMessageOuterClass.IMMessage build() {
        com.linseven.protobuf.IMMessageOuterClass.IMMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.linseven.protobuf.IMMessageOuterClass.IMMessage buildPartial() {
        com.linseven.protobuf.IMMessageOuterClass.IMMessage result = new com.linseven.protobuf.IMMessageOuterClass.IMMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.linseven.protobuf.IMMessageOuterClass.IMMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sourceUserId_ = sourceUserId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.destUserId_ = destUserId_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.content_ = content_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.groupId_ = groupId_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.sendTime_ = sendTime_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.linseven.protobuf.IMMessageOuterClass.IMMessage) {
          return mergeFrom((com.linseven.protobuf.IMMessageOuterClass.IMMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.linseven.protobuf.IMMessageOuterClass.IMMessage other) {
        if (other == com.linseven.protobuf.IMMessageOuterClass.IMMessage.getDefaultInstance()) return this;
        if (other.getSourceUserId() != 0) {
          setSourceUserId(other.getSourceUserId());
        }
        if (other.getDestUserId() != 0) {
          setDestUserId(other.getDestUserId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getGroupId() != 0) {
          setGroupId(other.getGroupId());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sourceUserId_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                destUserId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                content_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                type_ = input.readInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                groupId_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                sendTime_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int sourceUserId_ ;
      /**
       * <code>int32 sourceUserId = 1;</code>
       * @return The sourceUserId.
       */
      @java.lang.Override
      public int getSourceUserId() {
        return sourceUserId_;
      }
      /**
       * <code>int32 sourceUserId = 1;</code>
       * @param value The sourceUserId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceUserId(int value) {

        sourceUserId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sourceUserId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceUserId_ = 0;
        onChanged();
        return this;
      }

      private int destUserId_ ;
      /**
       * <code>int32 destUserId = 2;</code>
       * @return The destUserId.
       */
      @java.lang.Override
      public int getDestUserId() {
        return destUserId_;
      }
      /**
       * <code>int32 destUserId = 2;</code>
       * @param value The destUserId to set.
       * @return This builder for chaining.
       */
      public Builder setDestUserId(int value) {

        destUserId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 destUserId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        destUserId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        content_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        content_ = getDefaultInstance().getContent();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        content_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 4;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {

        type_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      private int groupId_ ;
      /**
       * <code>int32 groupId = 5;</code>
       * @return The groupId.
       */
      @java.lang.Override
      public int getGroupId() {
        return groupId_;
      }
      /**
       * <code>int32 groupId = 5;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(int value) {

        groupId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 groupId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        groupId_ = 0;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <code>int64 sendTime = 6;</code>
       * @return The sendTime.
       */
      @java.lang.Override
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <code>int64 sendTime = 6;</code>
       * @param value The sendTime to set.
       * @return This builder for chaining.
       */
      public Builder setSendTime(long value) {

        sendTime_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sendTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSendTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sendTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.linseven.protobuf.IMMessage)
    }

    // @@protoc_insertion_point(class_scope:com.linseven.protobuf.IMMessage)
    private static final com.linseven.protobuf.IMMessageOuterClass.IMMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.linseven.protobuf.IMMessageOuterClass.IMMessage();
    }

    public static com.linseven.protobuf.IMMessageOuterClass.IMMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IMMessage>
        PARSER = new com.google.protobuf.AbstractParser<IMMessage>() {
      @java.lang.Override
      public IMMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IMMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IMMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.linseven.protobuf.IMMessageOuterClass.IMMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_linseven_protobuf_IMMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_linseven_protobuf_IMMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"src/main/resources/IMMessage.proto\022\025co" +
      "m.linseven.protobuf\"w\n\tIMMessage\022\024\n\014sour" +
      "ceUserId\030\001 \001(\005\022\022\n\ndestUserId\030\002 \001(\005\022\017\n\007co" +
      "ntent\030\003 \001(\t\022\014\n\004type\030\004 \001(\005\022\017\n\007groupId\030\005 \001" +
      "(\005\022\020\n\010sendTime\030\006 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_linseven_protobuf_IMMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_linseven_protobuf_IMMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_linseven_protobuf_IMMessage_descriptor,
        new java.lang.String[] { "SourceUserId", "DestUserId", "Content", "Type", "GroupId", "SendTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
